#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx --no-install lint-staged &&

echo "\033[1;33mIniciando checagem de tipos...\033[0m" &&

npx tsc --noEmit --skipLibCheck &&

echo "\033[1;33mchecagem de tipos finalizada!\033[0m"